#!/usr/bin/env python3
# This file is part of the Luau programming language and is licensed under MIT License; see LICENSE.txt for details

from pathlib import Path

SIZES = (4, 16, 64, 256, 1024)
KINDS = ("if", "switch", "table", "function-table")
ITERATIONS = 2_000_000
OUT = Path(__file__).resolve().parent / "generated"


def expected_checksum(size):
    return sum((i * 73) % size for i in range(1, ITERATIONS + 1))


def dispatch(kind, size):
    if kind == "switch":
        lines = ["        switch value"]
        for i in range(size):
            lines.extend((f"            case {i} then", f"                result = {i}"))
        lines.extend(("            else", "                result = -1", "        end"))
        return lines

    if kind == "if":
        lines = []
        for i in range(size):
            keyword = "if" if i == 0 else "elseif"
            lines.extend((f"        {keyword} value == {i} then", f"            result = {i}"))
        lines.extend(("        else", "            result = -1", "        end"))
        return lines

    if kind == "table":
        return ["        result = lookup[value] or -1"]

    if kind == "function-table":
        return ["        result = handlers[value]()"]

    raise ValueError(kind)


def source(kind, size):
    setup = ""
    if kind == "table":
        entries = ", ".join(f"[{i}] = {i}" for i in range(size))
        setup = f"local lookup = {{{entries}}}\n"
    elif kind == "function-table":
        entries = ", ".join(f"[{i}] = function() return {i} end" for i in range(size))
        setup = f"local handlers = {{{entries}}}\n"

    return f'''-- This file is generated by bench/switch/generate.py; do not edit.
local function prequire(name) local success, result = pcall(require, name); return success and result end
local bench = script and require(script.Parent.Parent.bench_support) or prequire("bench_support") or require("../../bench_support")

{setup}local function test()
    local result = 0
    local checksum = 0

    for i = 1, {ITERATIONS} do
        local value = (i * 73) % {size}
{chr(10).join(dispatch(kind, size))}
        checksum += result
    end

    assert(checksum == {expected_checksum(size)})
end

bench.runCode(test, "{kind}-{size}")
'''


OUT.mkdir(parents=True, exist_ok=True)
for old in OUT.glob("*.luau"):
    old.unlink()

for size in SIZES:
    for kind in KINDS:
        (OUT / f"{kind}-{size}.luau").write_text(source(kind, size), newline="\n")

print(f"generated {len(SIZES) * len(KINDS)} switch benchmarks in {OUT}")
